\c superhero_dev
INSERT INTO superhero (
		image,
		name,
		fullname,
		location,
		intelligence,
		strength,
		speed,
		durability,
		power,
		combat,
		connections
	)
VALUES (
		'https://upload.wikimedia.org/wikipedia/en/f/fa/Chloe_Bennet_as_Daisy_Johnson.jpg',
		'Quake',
		'Daisy Louise Johnson',
		'New Orleans, Louisiana',
		70,
		25,
		25,
		30,
		70,
		90,
		'Calvin Zabo ( Mr. Hyde , father), Jennifer Johnson (mother), Greggory Sutter (adoptive father), Janet Sutter (adoptive mother), Secret Warriors, Avengers, Marvel Knights, Inhumans, S.H.I.E.L.D.'
	),
	(
		'https://i.pinimg.com/1200x/c0/05/d0/c005d046f110342329b821da2d6d0a90.jpg',
		'Wiccan',
		'Billy Kaplan',
		'Leonia, New Jersey(Allegedly)',
		50,
		35,
		75,
		60,
		100,
		30,
		'Wanda Maximoff/Scarlet Witch (biological mother), Thomas Shepherd/Speed (biological brother), Jeff Kaplan (adopted father), Rebecca Kaplan (adopted mother), Teddy Altman/Hulkling (love interest, husband), Young Avengers, Gods'
	),
	(
		'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/157-captain-marvel.jpg',
		'Captain Marvel',
		'Carol Danvers',
		'Boston, Massachusetts',
		84,
		88,
		71,
		95,
		100,
		90,
		'currently Avengers, former companion to the X-Men (as Carol Danvers), former member of the Starjammers (as Binary), Former Avenger (as Ms. Marvel), 
    	Marie Danvers (mother), Joseph Danvers, Sr. (father), Joseph Danvers, Jr. (brother), Steve Danvers (brother, deceased), Marcus Immortus (Danvers) (\"son\", deceased)'
	),
	(
		'https://cdn.jsdelivr.net/gh/akabab/superhero-api@0.3.0/api/images/md/491-nightwing.jpg',
		'Nightwing',
		'Dick Grayson',
		'Gotham City',
		88,
		11,
		33,
		28,
		36,
		100,
		'Batman Family and the JLA; formerly the Teen Titans, the New Titans, the Titans and the Outsiders, John Grayson (father, deceased), Mary Grayson (mother, deceased), Bruce Wayne / Batman (adoptive father), Damian Wayne / Robin (foster brother), Jason Todd / Red Hood (adoptive brother), Tim Drake / Red Robin (adoptive brother), Cassandra Cain / Batgirl IV (adoptive sister)'
	),
	(
		'https://upload.wikimedia.org/wikipedia/en/5/57/Angel_%28Buffy_the_Vampire_Slayer%29.jpg',
		'Angel',
		'Laim',
		'-',
		75,
		30,
		58,
		90,
		100,
		75,
		'Buffy, Kathy (sister), Connor (son), Twilight(\ "child\")'
	),
	(
		'https://oyster.ignimgs.com/mediawiki/apis.ign.com/buffy-the-vampire-slayer/9/99/Buffysummers.jpg',
		'Buffy',
		'Buffy Anne Summers',
		'-',
		63,
		28,
		42,
		70,
		48,
		60,
		'Slayer Army, Scooby Gang, (formerly) The Initiative, Watchers Council, Joyce Summers (mother, deceased), Hank Summers (father), Dawn Summers (sister), Celia (cousin, deceased), Arlene (aunt)'
	),
	(
		'https://i.imgur.com/x0oTNzV.jpg',
		'Commander Shepherd',
		'-',
		'-',
		75,
		30,
		30,
		30,
		65,
		90,
		'Kaidan Alenko,
		Tali,
		Liara,
		Garrus Vakarian,
		Ashley Williams,
		Urdnot Wrex,
		Kasumi Goto,
		Grunt,
		Thane Krios,
		Jack,
		Miranda Lawson,
		Legion,
		Zaeed Massani,
		Samara / Morinth,
		Mordin Solus,
		Jacob Taylor,
		Javik,
		James Vega,
		EDI,
		Nyreen Kandros'
),
(
	'https://www.giantbomb.com/a/uploads/scale_small/6/62890/1688536-lightning_03.jpg',
	'Lighting',
	'Claire Farron',
	'Bodhum',
	70,
	90,
	100,
	100,
	100,
	100,
	'Oerba Dia Vanille, Serah Farron, Snow Villiers, Hope Estheim, Sazh Katzroy, Oerba Yun Fang, Noel Kreiss'
),
(
	'https://upload.wikimedia.org/wikipedia/en/thumb/7/7d/Black_Lightning_%28Cress_Williams%29.jpg/170px-Black_Lightning_%28Cress_Williams%29.jpg',
	'Black Lighting',
	'Jefferson Pierce',
	'Southside Metropolis',
	50,
	35,
	80,
	40,
	60,
	70,
	'Alvin Pierce (father, deceased), Lynn Stewart (ex - wife), Anissa Pierce (daughter), Jennifer Pierce (daughter)'
);